#!/usr/bin/env bash

SAMPLE="$1"
OUTDIR="${PROJECT_DIR}/out/phase1"

echo Dump info and prefetch "$SAMPLE"
date

time vdb-dump --info "$SAMPLE"

time prefetch --max-size 1000000000  "$SAMPLE" --output-file "${OUTDIR}/${SAMPLE}.sra"

echo Validate "$SAMPLE"
date

time vdb-validate "${OUTDIR}/${SAMPLE}.sra"

echo "$SAMPLE" validation completed
date

