#!/usr/bin/env bash

set -euo pipefail

SAMPLE="$1"
IN_DIR="${PROJECT_DIR}/out/phase1"
OUT_DIR="${PROJECT_DIR}/out/phase2/${SAMPLE}"

echo Run Cell Ranger count on sample "$SAMPLE"
date

mkdir -p "$OUT_DIR"

time "$CELLRANGER_PATH" count --sample="$SAMPLE" \
	--transcriptome="$TRANSCRIPTOME_PATH" \
	--id="CRCD-${SAMPLE}" \
	--fastqs="$IN_DIR" \
	--output-dir="$OUT_DIR" \
	--create-bam=true \
	--disable-ui \
	--chemistry=ARC-v1

echo Cell Ranger count finished running on sample "$SAMPLE"
date
